import Foundation

/// CharacterManager - Manages spawning and resetting Characters
class CharacterManager {
	
	private var enemyList: [Character] = [

		Character(name: "Skeleton",
				  stats: Stats(),
				  maxHealth: 15,
				  currentHealth: 15,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 1,
				  currentArmor: 0,
				  maxDamage: 5,
				  minDamage: 2,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Zombie",
				  stats: Stats(),
				  maxHealth: 17,
				  currentHealth: 17,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 1,
				  currentArmor: 0,
				  maxDamage: 6,
				  minDamage: 3,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Golem",
				  stats: Stats(),
				  maxHealth: 19,
				  currentHealth: 19,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 2,
				  currentArmor: 0,
				  maxDamage: 7,
				  minDamage: 4,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Witch",
				  stats: Stats(),
				  maxHealth: 18,
				  currentHealth: 18,
				  maxMana: 10,
				  currentMana: 10,
				  maxEnergy: 5,
				  spellPower: 6,
				  currentEnergy: 5,
				  blockValue: 1,
				  currentArmor: 0,
				  maxDamage: 6,
				  minDamage: 3,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Vampire",
				  stats: Stats(),
				  maxHealth: 20,
				  currentHealth: 20,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 2,
				  currentEnergy: 5,
				  blockValue: 2,
				  currentArmor: 0,
				  maxDamage: 7,
				  minDamage: 4,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),
		
		Character(name: "Mummy",
				  stats: Stats(),
				  maxHealth: 22,
				  currentHealth: 22,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 2,
				  currentArmor: 0,
				  maxDamage: 8,
				  minDamage: 5,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Giant Spider",
				  stats: Stats(),
				  maxHealth: 21,
				  currentHealth: 21,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 2,
				  currentArmor: 0,
				  maxDamage: 8,
				  minDamage: 4,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Werewolf",
				  stats: Stats(),
				  maxHealth: 23,
				  currentHealth: 23,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 2,
				  currentArmor: 0,
				  maxDamage: 9,
				  minDamage: 5,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Goblin",
				  stats: Stats(),
				  maxHealth: 16,
				  currentHealth: 16,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 1,
				  currentArmor: 0,
				  maxDamage: 5,
				  minDamage: 2,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Ogre",
				  stats: Stats(),
				  maxHealth: 25,
				  currentHealth: 25,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 3,
				  currentArmor: 0,
				  maxDamage: 10,
				  minDamage: 6,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Troll",
				  stats: Stats(),
				  maxHealth: 28,
				  currentHealth: 28,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 3,
				  currentArmor: 0,
				  maxDamage: 12,
				  minDamage: 7,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Dark Knight",
				  stats: Stats(),
				  maxHealth: 30,
				  currentHealth: 30,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 3,
				  currentArmor: 0,
				  maxDamage: 13,
				  minDamage: 8,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Dragon",
				  stats: Stats(),
				  maxHealth: 35,
				  currentHealth: 35,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 10,
				  currentEnergy: 5,
				  blockValue: 4,
				  currentArmor: 0,
				  maxDamage: 15,
				  minDamage: 10,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Demon",
				  stats: Stats(),
				  maxHealth: 32,
				  currentHealth: 32,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 8,
				  currentEnergy: 5,
				  blockValue: 3,
				  currentArmor: 0,
				  maxDamage: 14,
				  minDamage: 9,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: []),

		Character(name: "Griffin",
				  stats: Stats(),
				  maxHealth: 28,
				  currentHealth: 28,
				  maxMana: 0,
				  currentMana: 0,
				  maxEnergy: 5,
				  spellPower: 0,
				  currentEnergy: 5,
				  blockValue: 3,
				  currentArmor: 0,
				  maxDamage: 12,
				  minDamage: 7,
				  isAffected: false,
				  isStunned: false,
				  activeEffects: [])
	]


	func setupHero() -> Character {
		return Character(name: "Hieronius",
						 stats: Stats(),
						  maxHealth: 100,
						  currentHealth: 100,
						  maxMana: 100,
						  currentMana: 100,
						  maxEnergy: 5,
						 spellPower: 20,
						 currentEnergy: 5,
						 blockValue: 5,
						 currentArmor: 1,
						  maxDamage: 3,
						  minDamage: 2,
						 isAffected: false,
						 isStunned: false,
						 activeEffects: [])
	}

	func spawnEnemy(at index: Int) -> Character {
		return enemyList[index]
	}

}

